spring.application.name=cruddemo
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Employee
spring.datasource.username=postgres
spring.datasource.password=22G28

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Log the details of the request that failed
logging.level.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod=DEBUG
# Or log the payload itself
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG